//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_request
    {
        public string tg_chat_id { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
