//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public int id { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> answer_time { get; set; }
        public int user_id { get; set; }
        public int file_request_id { get; set; }
    
        public virtual file_request file_request { get; set; }
        public virtual user user { get; set; }
    }
}
