//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileEntitiesFinal : DbContext
    {
        public FileEntitiesFinal()
            : base("name=FileEntitiesFinal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<file_request> file_request { get; set; }
        public virtual DbSet<link_request> link_request { get; set; }
        public virtual DbSet<school> school { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_share_file> user_share_file { get; set; }
    }
}
